#define HORIZONTAL_RES 320
#define VERTICAL_RES 240
#define POSITION_OFFSET_Y 20
#define SIGNAL_LENGTH 512

#define SAMPLINGFREQUENCY 40000
#define SAMPLING_TIME_US (1000000UL/SAMPLINGFREQUENCY)
#define ANALOG_SIGNAL_INPUT M5STACKFIRE_MICROPHONE_PIN
